"""
reporter.py — Writes the final scan report in Markdown and JSON.

After all probes run, the reporter takes the list of results and
produces two files:
  - A Markdown file (.md) — human-readable, shareable with your team
  - A JSON file (.json) — machine-readable, usable in CI pipelines

The Markdown report starts with a risk summary so the headline result
is visible without reading the whole thing.
"""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

from .models import ProbeResult, Severity, Verdict

# Severity ordering for sorting (worst first)
_SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    None: 4,
}

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
    None: "✅",
}


def write_reports(
    results: list[ProbeResult],
    target_id: str,
    output_dir: str = "reports",
) -> tuple[Path, Path]:
    """
    Write Markdown and JSON reports.
    Returns (markdown_path, json_path).
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    md_path = out / f"{ts}_report.md"
    json_path = out / f"{ts}_report.json"

    md_path.write_text(_build_markdown(results, target_id, ts), encoding="utf-8")
    json_path.write_text(_build_json(results, target_id, ts), encoding="utf-8")

    return md_path, json_path


def _counts(results: list[ProbeResult]) -> dict:
    total = len(results)
    fails = [r for r in results if r.verdict == Verdict.FAIL]
    passes = [r for r in results if r.verdict == Verdict.PASS]
    inconclusive = [r for r in results if r.verdict == Verdict.INCONCLUSIVE]
    by_severity: dict[str, int] = {}
    for r in fails:
        key = r.severity.value if r.severity else "unknown"
        by_severity[key] = by_severity.get(key, 0) + 1
    return {
        "total": total,
        "fail": len(fails),
        "pass": len(passes),
        "inconclusive": len(inconclusive),
        "by_severity": by_severity,
    }


def _overall_risk(counts: dict) -> str:
    sev = counts["by_severity"]
    if sev.get("critical", 0) > 0:
        return "🔴 CRITICAL"
    if sev.get("high", 0) > 0:
        return "🟠 HIGH"
    if sev.get("medium", 0) > 0:
        return "🟡 MEDIUM"
    if sev.get("low", 0) > 0:
        return "🟢 LOW"
    return "✅ PASS — No issues found"


def _build_markdown(results: list[ProbeResult], target_id: str, ts: str) -> str:
    c = _counts(results)
    lines = [
        "# LLM Red-Team Scan Report",
        "",
        f"**Target:** `{target_id}`  ",
        f"**Run timestamp:** {ts}  ",
        f"**Total probes:** {c['total']}  ",
        "",
        "## Risk Summary",
        "",
        f"| Overall Risk | Failures | Passes | Inconclusive |",
        f"|---|---|---|---|",
        f"| {_overall_risk(c)} | {c['fail']} | {c['pass']} | {c['inconclusive']} |",
        "",
    ]

    if c["by_severity"]:
        lines += ["**Failures by severity:**", ""]
        for sev, count in sorted(c["by_severity"].items()):
            lines.append(f"- {sev.upper()}: {count}")
        lines.append("")

    lines += ["---", "", "## Probe Results", ""]

    sorted_results = sorted(results, key=lambda r: _SEVERITY_ORDER.get(r.severity, 4))

    for r in sorted_results:
        emoji = _SEVERITY_EMOJI.get(r.severity, "✅")
        sev_label = r.severity.value.upper() if r.severity else "—"
        lines += [
            f"### {emoji} `{r.probe_id}`",
            "",
            f"| Field | Value |",
            f"|---|---|",
            f"| Category | `{r.category}` |",
            f"| Verdict | **{r.verdict.value.upper()}** |",
            f"| Severity | {sev_label} |",
            f"| Reason | {r.reason} |",
            "",
        ]
        if r.response_snippet:
            lines += [
                "**Model response (first 200 chars):**",
                f"```",
                r.response_snippet,
                "```",
                "",
            ]
        if r.verdict == Verdict.FAIL and r.remediation:
            lines += [
                "**Remediation:**",
                f"> {r.remediation}",
                "",
            ]
        lines.append("---")
        lines.append("")

    lines += [
        "## Responsible Use",
        "",
        "This report was generated by the LLM Red-Team Framework.",
        "It is intended for authorized security testing only.",
        "Do not use findings to attack systems you do not own or have permission to test.",
    ]

    return "\n".join(lines)


def _build_json(results: list[ProbeResult], target_id: str, ts: str) -> str:
    c = _counts(results)
    payload = {
        "target": target_id,
        "timestamp": ts,
        "summary": c,
        "overall_risk": _overall_risk(c),
        "results": [r.model_dump() for r in results],
    }
    return json.dumps(payload, indent=2, default=str)
